from django.urls import path

from kitchen import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('search/', views.search, name='search'),
    path('products/', views.product_list, name='product_list'),
    path('products/new/', views.product_create, name='product_create'),
    path('products/<int:pk>/edit/', views.product_edit, name='product_edit'),
    path('products/<int:pk>/toggle/', views.product_toggle, name='product_toggle'),
    path('categories/new/', views.category_create, name='category_create'),
    path('suppliers/', views.supplier_list, name='supplier_list'),
    path('suppliers/new/', views.supplier_create, name='supplier_create'),
    path('suppliers/<int:pk>/edit/', views.supplier_edit, name='supplier_edit'),
    path('stock/', views.stock_list, name='stock_list'),
    path('stock/<int:pk>/adjust/', views.stock_adjust, name='stock_adjust'),
    path('receipts/', views.receipt_list, name='receipt_list'),
    path('receipts/new/', views.receipt_create, name='receipt_create'),
    path('receipts/export/', views.receipt_export, name='receipt_export'),
    path('recipes/', views.recipe_list, name='recipe_list'),
    path('recipes/new/', views.recipe_create, name='recipe_create'),
    path('recipes/<int:pk>/', views.recipe_detail, name='recipe_detail'),
    path('recipes/<int:pk>/edit/', views.recipe_edit, name='recipe_edit'),
    path('recipes/<int:pk>/print/', views.recipe_print, name='recipe_print'),
    path('recipes/<int:pk>/pdf/', views.recipe_pdf_view, name='recipe_pdf'),
    path('cook/', views.cook_create, name='cook_create'),
    path('cook/preview/', views.cook_preview_htmx, name='cook_preview'),
    path('cook/history/', views.cook_history, name='cook_history'),
    path('cook/<int:pk>/', views.cook_detail, name='cook_detail'),
    path('cook/<int:pk>/cancel/', views.cook_cancel, name='cook_cancel'),
    path('cook/<int:pk>/print/', views.cook_print, name='cook_print'),
    path('cook/<int:pk>/pdf/', views.cook_pdf_view, name='cook_pdf'),
    path('waste/', views.waste_list, name='waste_list'),
    path('waste/new/', views.waste_create, name='waste_create'),
    path('menu/', views.menu_day, name='menu_day'),
    path('menu/fill-portions/', views.menu_fill_portions, name='menu_fill_portions'),
    path('menu/items/<int:pk>/cook/', views.menu_cook_item, name='menu_cook_item'),
    path('menu/templates/', views.menu_templates, name='menu_templates'),
    path('menu/templates/new/', views.menu_template_create, name='menu_template_create'),
    path('menu/templates/<int:pk>/edit/', views.menu_template_edit, name='menu_template_edit'),
    path('menu/templates/apply/', views.menu_apply_template, name='menu_apply_template'),
    path('headcount/', views.headcount_list, name='headcount_list'),
    path('shopping/', views.shopping_list, name='shopping_list'),
    path('shopping/export/', views.shopping_export, name='shopping_export'),
    path('shopping/print/', views.shopping_print, name='shopping_print'),
    path('shopping/pdf/', views.shopping_pdf_view, name='shopping_pdf'),
    path('budget/', views.budget_page, name='budget_page'),
    path('audit/', views.audit_list, name='audit_list'),
    path('notifications/dismiss/', views.notification_dismiss, name='notification_dismiss'),
    path('notifications/dismiss-all/', views.notification_dismiss_all, name='notification_dismiss_all'),
    path('reports/', views.reports, name='reports'),
    path('reports/export-out/', views.reports_export_out, name='reports_export_out'),
    path('reports/export-cooks/', views.reports_export_cooks, name='reports_export_cooks'),
    path('reports/print/', views.reports_print, name='reports_print'),
    path('reports/pdf/', views.reports_pdf_view, name='reports_pdf'),
]
