# Generated by Django 5.2.17 on 2026-08-25 11:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Kunlik menyu',
                'verbose_name_plural': 'Kunlik menyular',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MenuTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Nonushta'), ('lunch', 'Tushlik'), ('dinner', 'Kechki ovqat'), ('other', 'Boshqa')], default='lunch', max_length=20, verbose_name='Ovqat turi')),
                ('base_portions', models.PositiveIntegerField(default=1, verbose_name='Baza porsiya')),
                ('allergens', models.CharField(blank=True, max_length=255, verbose_name='Allergenlar')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Retsept',
                'verbose_name_plural': 'Retseptlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Yetkazib beruvchi',
                'verbose_name_plural': 'Yetkazib beruvchilar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('entity', models.CharField(max_length=80)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CookBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions', models.PositiveIntegerField()),
                ('cooked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cost_per_portion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_kcal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('kcal_per_portion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('protein_per_portion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('fat_per_portion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('carbs_per_portion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('status', models.CharField(choices=[('done', 'Bajarildi'), ('cancelled', 'Bekor')], default='done', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cook_batches', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='kitchen.recipe')),
            ],
            options={
                'verbose_name': 'Pishirish',
                'verbose_name_plural': 'Pishirishlar',
                'ordering': ['-cooked_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyHeadcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('1', '1-smena'), ('2', '2-smena')], max_length=2)),
                ('people_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'shift'],
                'unique_together': {('date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('l', 'l'), ('dona', 'dona'), ('g', 'g')], default='kg', max_length=10, verbose_name='Birlik')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Qoldiq')),
                ('avg_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='O‘rtacha tannarx')),
                ('min_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Min qoldiq')),
                ('kcal_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Kkal / birlik')),
                ('protein', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Oqsil g')),
                ('fat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Yog‘ g')),
                ('carbs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Uglevod g')),
                ('allergens', models.CharField(blank=True, max_length=255, verbose_name='Allergenlar')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Muddat')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='kitchen.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CookBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('line_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitchen.cookbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kitchen.product')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='MenuTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Nonushta'), ('lunch', 'Tushlik'), ('dinner', 'Kechki ovqat'), ('other', 'Boshqa')], default='lunch', max_length=20)),
                ('portions', models.PositiveIntegerField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitchen.menutemplate')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kitchen.recipe')),
            ],
            options={
                'ordering': ['weekday', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='DailyMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Nonushta'), ('lunch', 'Tushlik'), ('dinner', 'Kechki ovqat'), ('other', 'Boshqa')], default='lunch', max_length=20)),
                ('portions', models.PositiveIntegerField(default=1)),
                ('is_cooked', models.BooleanField(default=False)),
                ('cook_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='kitchen.cookbatch')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitchen.dailymenu')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kitchen.recipe')),
            ],
            options={
                'ordering': ['meal_type', 'recipe__name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Prixod'), ('out', 'Rasxod'), ('adjust', 'Tuzatish'), ('waste', 'Chiqindi')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cook_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='kitchen.cookbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='kitchen.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='kitchen.supplier')),
            ],
            options={
                'verbose_name': 'Ombor harakati',
                'verbose_name_plural': 'Ombor harakatlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_portion', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_items', to='kitchen.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitchen.recipe')),
            ],
            options={
                'ordering': ['product__name'],
                'unique_together': {('recipe', 'product')},
            },
        ),
    ]
