# Generated by Django 5.2.17 on 2026-08-25 12:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='1 birlikdagi uglevod (gramm)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Uglevod g / 1 birlik'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='1 birlikdagi yog‘ (gramm)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Yog‘ g / 1 birlik'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kcal_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Masalan 1 kg yoki 1 litr uchun', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Kkal / 1 birlik'),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='1 kg/l/dona ichidagi oqsil (gramm). 100 g da 26 g bo‘lsa, 1 kg da 260', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Oqsil g / 1 birlik'),
        ),
    ]
