# Generated by Django 5.2.17 on 2026-09-03 06:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_nutrition_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HygieneCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_type', models.CharField(choices=[('temp', 'Harorat'), ('clean', 'Tozalik'), ('hand', 'Qo‘l gigiyenasi'), ('other', 'Boshqa')], max_length=12)),
                ('is_ok', models.BooleanField(default=True)),
                ('value', models.CharField(blank=True, help_text='Masalan harorat °C', max_length=80)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('ordered', 'Buyurtma'), ('received', 'Qabul qilingan'), ('cancelled', 'Bekor')], default='draft', max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('ordered_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('adjust', 'Tuzatish'), ('waste', 'Chiqindi')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('new_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Partiya',
                'verbose_name_plural': 'Partiyalar',
                'ordering': ['expiry_date', 'received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockLotAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nomi')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='Kod')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ombor joyi',
                'verbose_name_plural': 'Ombor joylari',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cookbatch',
            name='shift',
            field=models.CharField(blank=True, choices=[('1', '1-smena'), ('2', '2-smena')], default='', max_length=2, verbose_name='Smena'),
        ),
        migrations.AlterField(
            model_name='cookbatch',
            name='status',
            field=models.CharField(choices=[('queued', 'Navbat'), ('cooking', 'Tayyorlanmoqda'), ('done', 'Bajarildi'), ('cancelled', 'Bekor')], default='done', max_length=20),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='kit_audit_created'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='kit_audit_action'),
        ),
        migrations.AddIndex(
            model_name='cookbatch',
            index=models.Index(fields=['-cooked_at'], name='kit_cook_cooked'),
        ),
        migrations.AddIndex(
            model_name='cookbatch',
            index=models.Index(fields=['status', '-cooked_at'], name='kit_cook_status'),
        ),
        migrations.AddField(
            model_name='hygienecheck',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='kitchen.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kitchen.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kitchen.product'),
        ),
        migrations.AddField(
            model_name='stockchangerequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='kitchen.product'),
        ),
        migrations.AddField(
            model_name='stockchangerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockchangerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_change_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='kitchen.product'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='source_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lots', to='kitchen.stockmovement'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='kitchen.supplier'),
        ),
        migrations.AddField(
            model_name='stocklotallocation',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='kitchen.stocklot'),
        ),
        migrations.AddField(
            model_name='stocklotallocation',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_allocations', to='kitchen.stockmovement'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='kitchen.storagelocation'),
        ),
        migrations.AddField(
            model_name='hygienecheck',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hygiene_checks', to='kitchen.storagelocation'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='kitchen.storagelocation', verbose_name='Asosiy joy'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='kitchen.storagelocation'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'quantity'], name='kit_prod_active_qty'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['expiry_date'], name='kit_prod_expiry'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['-created_at'], name='kit_move_created'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='kit_move_type_created'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', '-created_at'], name='kit_move_prod_created'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['product', 'expiry_date', 'received_at'], name='kit_lot_fefo'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['product', 'quantity'], name='kit_lot_prod_qty'),
        ),
    ]
