# Generated by Django 5.2.17 on 2026-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_seed_lots_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockchangerequest',
            name='requested_from_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
