# Generated by Django 5.2.17 on 2026-09-08 09:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_category_name_ci_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=120, verbose_name='Familiya')),
                ('employee_code', models.CharField(blank=True, max_length=40, verbose_name='Tabel / kod')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Bo‘lim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ishchi',
                'verbose_name_plural': 'Ishchilar',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='kit_worker_name'), models.Index(fields=['is_active', 'last_name'], name='kit_worker_active')],
            },
        ),
        migrations.CreateModel(
            name='MealCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Nonushta'), ('lunch', 'Tushlik'), ('dinner', 'Ujin')], max_length=20)),
                ('served_on', models.DateField(db_index=True, verbose_name='Sana')),
                ('served_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_checkins', to='kitchen.worker')),
            ],
            options={
                'verbose_name': 'Ovqatlanish',
                'verbose_name_plural': 'Ovqatlanishlar',
                'ordering': ['-served_at'],
                'indexes': [models.Index(fields=['served_on', 'meal_type'], name='kit_meal_day_type'), models.Index(fields=['meal_type', '-served_at'], name='kit_meal_type_time')],
                'constraints': [models.UniqueConstraint(fields=('worker', 'served_on', 'meal_type'), name='kit_meal_checkin_unique_day')],
            },
        ),
    ]
