# Generated by Django 5.2.17 on 2026-09-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_workers_meal_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenuitem',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Nonushta'), ('lunch', 'Tushlik'), ('afternoon', 'Kunduzgi'), ('dinner', 'Kechki ovqat'), ('other', 'Boshqa')], default='lunch', max_length=20),
        ),
        migrations.AlterField(
            model_name='mealcheckin',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Nonushta'), ('lunch', 'Tushlik'), ('afternoon', 'Kunduzgi'), ('dinner', 'Kechki ovqat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='menutemplateitem',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Nonushta'), ('lunch', 'Tushlik'), ('afternoon', 'Kunduzgi'), ('dinner', 'Kechki ovqat'), ('other', 'Boshqa')], default='lunch', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Nonushta'), ('lunch', 'Tushlik'), ('afternoon', 'Kunduzgi'), ('dinner', 'Kechki ovqat'), ('other', 'Boshqa')], default='lunch', max_length=20, verbose_name='Ovqat turi'),
        ),
    ]
