# Generated by Django 5.2.17 on 2026-09-10 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_meal_four_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcheckin',
            name='portions',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Porsiya'),
        ),
    ]
