# Generated by Django 5.2.17 on 2026-09-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0009_meal_checkin_portions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='include_in_meal_sverka',
            field=models.BooleanField(default=True, help_text='Asosiy ovqat uchun yoqilgan qoldiring. Salat, kefir, kompot kabi qo‘shimchalar uchun o‘chiring — ombordan yechiladi, lekin QR porsiya sverkasiga qo‘shilmaydi.', verbose_name='Ovqat sverkasiga kiradi'),
        ),
    ]
