# Generated by Django 5.2.17 on 2026-09-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0013_supplier_debt_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Prixod'), ('out', 'Rasxod'), ('adjust', 'Tuzatish'), ('waste', 'Chiqindi'), ('office', 'Ofis')], max_length=10),
        ),
    ]
